version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0  
  pre_build:
    commands: dotnet clean dotnet-console.csproj 
  build:
    commands:
      - dotnet build -c Release dotnet-console.csproj
  post_build:
    commands:
      - dotnet run bin\Release\net5.0\dotnet-console.dll
artifacts:
  files:
    - '**/*'
