version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0  
  build:
    commands:
      - dotnet build -c Release
  post_build:
    commands:
      - dotnet run 
artifacts:
  files:
    - '**/*'
