version: 0.2

phases:
  install:
    install:
        runtime-versions:
            dotnet: 3.1  
  build:
    commands:
      - dotnet build -c Release
  post_build:
    commands:
      - dotnet run bin\Debug\netcoreapp2.1\publish\dotnet-console.dll
artifacts:
  files:
    - '**/*'
