version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 5.0  
  pre_build:
    commands: dotnet clean dotnet-console.csproj 
  build:
    commands:
      - dotnet build dotnet-console.csproj -c Release
  post_build:
    commands:
      - bin\Debug\net5.0\dotnet-console.exe
artifacts:
  files:
    - '**/*'
